### ISSUE TITLE
SoundCloud.Net DLL is missing

### ISSUE THREAD

**Issue by asalhani** [kagasu/SoundCloudLikeDownloader#1]
When I cloned the solution then tried to build it, I'm getting the blow compilation error message:

"The type or namespace name 'SoundCloud' could not be found (are you missing a using directive or an assembly reference?)"

Please upload missing DLL and check-in your code again.

thanks....

**Comment by kagasu** [comment]
Use this Wrapper.

Haythem/SoundCloud.NET
https://github.com/Haythem/SoundCloud.NET

1) compile it.
2) Add assembly reference "SoundCloud.NET.dll"

**Comment by asalhani** [comment]
Dear @kagasu ,
I added the mentioned project DLL, but it seems that it has been updated becouse i'm getting the below compilation error now:

"No overload for method 'GetFavorites' takes 1 arguments    C:\Users\Administrator\Desktop\new soundcloud pro\SoundCloudLikeDownloader-master\SoundCloudLikeDownloader\MainWindow.xaml.cs"

"'SoundCloud.NET.SoundCloudClient' does not contain a definition for 'getClientID' and no extension method 'getClientID' accepting a first argument of type 'SoundCloud.NET.SoundCloudClient' could be found (are you missing a using directive or an assembly reference?)  C:\Users\Administrator\Desktop\new soundcloud pro\SoundCloudLikeDownloader-master\SoundCloudLikeDownloader\MainWindow.xaml.cs"

thanks in advance...

**Comment by kagasu** [comment]
sry.
I had forgot to fork.

try this one.
https://github.com/kagasu/SoundCloud.NET

**Comment by asalhani** [comment]
It's working now...
thanks..
