### ISSUE TITLE
GetFavorites() function returns only top 50 tracks

### ISSUE THREAD

**Issue by asalhani** [kagasu/SoundCloudLikeDownloader#2]
When calling GetFavorites() function, the returned JSON response contains only top 50 tracks. However, I'm sure that my account contains +300 Favorited tracks.

Is this limitation from SoundCloud API or in the API wrapper?

**Comment by kagasu** [comment]
The number of items in the collection returned is limited to 50 by default with a maximum value of 200.

https://developers.soundcloud.com/docs#pagination

**Comment by asalhani** [comment]
Then, we need to update request URI to accept following parameters in order to support API paging functionality:
- Page Size
- Current page index

**Comment by kagasu** [comment]
corresponding to pagination limit

``` Csharp
var page_index = 0;
var page_size = 200;
var favorites = User.Me().GetFavorites(index, page_size);
```

https://github.com/kagasu/SoundCloud.NET/commit/f96a725f78e6f10ed2dc1eb71b378c8912398dba#diff-4a07f4aa900afbc0f00ab7ef2d263e56

**Comment by asalhani** [comment]
Great work @kagasu .. I will try it and let you know...
Thanks :)

**Comment by asalhani** [comment]
@kagasu Bad news. I was just reading on SoundCloud developer blog, there is announcement that the partitioning through Offset parameter will be depreciated by March.

Blog link:
https://developers.soundcloud.com/blog/offset-pagination-deprecated

**Comment by kagasu** [comment]
support new pagination.

https://github.com/kagasu/SoundCloudLikeDownloader/commit/4461757ab46765a66213c4c162dd7fc8fb99b3bb
https://github.com/kagasu/SoundCloud.NET/commit/1fa2b549639db86b2364da4e619092d4fe116402
